/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as frontendIndexRouteImport } from './routes/(frontend)/index'

const frontendIndexRoute = frontendIndexRouteImport.update({
  id: '/(frontend)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof frontendIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof frontendIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(frontend)/': typeof frontendIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/(frontend)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  frontendIndexRoute: typeof frontendIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(frontend)/': {
      id: '/(frontend)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof frontendIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  frontendIndexRoute: frontendIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
