/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import type { getRouter } from "./router.tsx";
import { Route as adminLayoutRouteImport } from "./routes/(admin)/_layout";
import { Route as adminLayoutProtectedRouteImport } from "./routes/(admin)/_layout/_protected";
import { Route as adminLayoutProtectedAdminRouteImport } from "./routes/(admin)/_layout/_protected/admin";
import { Route as adminLayoutLoginRouteImport } from "./routes/(admin)/_layout/login";
import { Route as frontendIndexRouteImport } from "./routes/(frontend)/index";
import { Route as rootRouteImport } from "./routes/__root";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as ApiImageRouteImport } from "./routes/api/image";
import type { createStart } from "@tanstack/react-start";

const frontendIndexRoute = frontendIndexRouteImport.update({
  id: "/(frontend)/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiImageRoute = ApiImageRouteImport.update({
  id: "/api/image",
  path: "/api/image",
  getParentRoute: () => rootRouteImport,
} as any);
const adminLayoutRoute = adminLayoutRouteImport.update({
  id: "/(admin)/_layout",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const adminLayoutLoginRoute = adminLayoutLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => adminLayoutRoute,
} as any);
const adminLayoutProtectedRoute = adminLayoutProtectedRouteImport.update({
  id: "/_protected",
  getParentRoute: () => adminLayoutRoute,
} as any);
const adminLayoutProtectedAdminRoute =
  adminLayoutProtectedAdminRouteImport.update({
    id: "/admin",
    path: "/admin",
    getParentRoute: () => adminLayoutProtectedRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/api/image": typeof ApiImageRoute;
  "/": typeof frontendIndexRoute;
  "/login": typeof adminLayoutLoginRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/admin": typeof adminLayoutProtectedAdminRoute;
}
export interface FileRoutesByTo {
  "/api/image": typeof ApiImageRoute;
  "/": typeof frontendIndexRoute;
  "/login": typeof adminLayoutLoginRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/admin": typeof adminLayoutProtectedAdminRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/(admin)/_layout": typeof adminLayoutRouteWithChildren;
  "/api/image": typeof ApiImageRoute;
  "/(frontend)/": typeof frontendIndexRoute;
  "/(admin)/_layout/_protected": typeof adminLayoutProtectedRouteWithChildren;
  "/(admin)/_layout/login": typeof adminLayoutLoginRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/(admin)/_layout/_protected/admin": typeof adminLayoutProtectedAdminRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/api/image" | "/" | "/login" | "/api/auth/$" | "/admin";
  fileRoutesByTo: FileRoutesByTo;
  to: "/api/image" | "/" | "/login" | "/api/auth/$" | "/admin";
  id:
    | "__root__"
    | "/(admin)/_layout"
    | "/api/image"
    | "/(frontend)/"
    | "/(admin)/_layout/_protected"
    | "/(admin)/_layout/login"
    | "/api/auth/$"
    | "/(admin)/_layout/_protected/admin";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  adminLayoutRoute: typeof adminLayoutRouteWithChildren;
  ApiImageRoute: typeof ApiImageRoute;
  frontendIndexRoute: typeof frontendIndexRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(frontend)/": {
      id: "/(frontend)/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof frontendIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/image": {
      id: "/api/image";
      path: "/api/image";
      fullPath: "/api/image";
      preLoaderRoute: typeof ApiImageRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(admin)/_layout": {
      id: "/(admin)/_layout";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof adminLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(admin)/_layout/login": {
      id: "/(admin)/_layout/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof adminLayoutLoginRouteImport;
      parentRoute: typeof adminLayoutRoute;
    };
    "/(admin)/_layout/_protected": {
      id: "/(admin)/_layout/_protected";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof adminLayoutProtectedRouteImport;
      parentRoute: typeof adminLayoutRoute;
    };
    "/(admin)/_layout/_protected/admin": {
      id: "/(admin)/_layout/_protected/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof adminLayoutProtectedAdminRouteImport;
      parentRoute: typeof adminLayoutProtectedRoute;
    };
  }
}

interface adminLayoutProtectedRouteChildren {
  adminLayoutProtectedAdminRoute: typeof adminLayoutProtectedAdminRoute;
}

const adminLayoutProtectedRouteChildren: adminLayoutProtectedRouteChildren = {
  adminLayoutProtectedAdminRoute: adminLayoutProtectedAdminRoute,
};

const adminLayoutProtectedRouteWithChildren =
  adminLayoutProtectedRoute._addFileChildren(adminLayoutProtectedRouteChildren);

interface adminLayoutRouteChildren {
  adminLayoutProtectedRoute: typeof adminLayoutProtectedRouteWithChildren;
  adminLayoutLoginRoute: typeof adminLayoutLoginRoute;
}

const adminLayoutRouteChildren: adminLayoutRouteChildren = {
  adminLayoutProtectedRoute: adminLayoutProtectedRouteWithChildren,
  adminLayoutLoginRoute: adminLayoutLoginRoute,
};

const adminLayoutRouteWithChildren = adminLayoutRoute._addFileChildren(
  adminLayoutRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  adminLayoutRoute: adminLayoutRouteWithChildren,
  ApiImageRoute: ApiImageRoute,
  frontendIndexRoute: frontendIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
